# @package _global_
recorder:
  _target_: linker_sim.io.recorder.Recorder
  sink:
    _target_: linker_sim.io.recorder.NullSink
  cfg:
    _target_: linker_sim.io.recorder.RecorderCfg
    enabled: false
    record_every_env: false
